// <auto-generated />
using System;
using Blog.Services.WebScraper.Infrastructure.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blog.Services.WebScraper.Infrastructure.EF.Migrations
{
    [DbContext(typeof(ScrapedArticleWriteDbContext))]
    partial class ScrapedArticleWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blog.Services.WebScraper.Domain.ScrapedArticles.Entities.ScrapeArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAlreadyUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScrapeArticles", (string)null);
                });

            modelBuilder.Entity("Blog.Services.WebScraper.Domain.ScrapedArticles.Entities.ScrapeArticle", b =>
                {
                    b.OwnsOne("Blog.Services.WebScraper.Domain.ValueObjects.Provider.Provider", "Provider", b1 =>
                        {
                            b1.Property<Guid>("ScrapeArticleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Provider");

                            b1.HasKey("ScrapeArticleId");

                            b1.ToTable("ScrapeArticles");

                            b1.WithOwner()
                                .HasForeignKey("ScrapeArticleId");
                        });

                    b.Navigation("Provider");
                });
#pragma warning restore 612, 618
        }
    }
}
