services:

  blog.apigateway:
    image: blog.apigateway
    container_name: Blog.ApiGateway
    build:
      context: .
      dockerfile: src/ApiGateway/Blog.APIGateway/Dockerfile

  blog.database:
    image: postgres:latest
    container_name: Blog.Database 
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432 

  blog.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: Blog.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
